### ISSUE TITLE
if text start with bold, fail

### ISSUE THREAD

**Issue by shargon** [henck/rtf-html-php#1]
When a text start with bold, the text is show as normal font

**this is the raw Text**

{\rtf1\ansi\ansicpg1252\deff0\deflang3082{\fonttbl{\f0\fnil\fcharset0 Courier New;}}
\viewkind4\uc1\pard\b\f0\fs17 VIT.O.BEST WHEY PROTEIN 100% 4LB\b0 . dentro del mundo de los suplementos deportivos es posiblemente es la mejor prote\''edna en cuanto a calidad/precio del re\''f1ido mercado de la nutrici\''f3n deportiva.\par
\par
\par
\b VIT.O.BEST WHEY PROTEIN 100% 24B\b0 . es una prote\''edna perfecta para el uso diario, que adem\''e1s tiene una buena capacidad de absorci\''f3n y una velocidad de absorci\''f3n media.\par
\par
\par
\b VIT.O.BEST WHEY PROTEIN 100%\b0  tiene una gran variedad de sabores deliciosos y muy suaves perfectos para el uso diario sin que terminen siendo empalagosos o \b aburridos. WHEY PROTEIN 100%\b0  est\''e1 disponible en sabor a chocolate, yogur de lim\''f3n , fresa, crema de caf\''e9 y vainilla. \b VIT.O.BEST WHEY PROTEIN 100% \b0 es una prote\''edna muy pura que no contiene az\''facar y est\''e1 totalemente libre de aspartamo.\par
}

**this is the dump**

{
    WORD rtf (1)
    WORD ansi\ansicpg (1252)
    WORD deff (0)
    WORD deflang (3082)
    WORD viewkind (4)
    WORD uc (1)
    WORD pard\b\f (0)
    WORD fs (17)
    TEXT VIT.O.BEST WHEY PROTEIN 100% 4LB
    WORD b (0)
    TEXT . dentro del mundo de los suplementos deportivos es posiblemente es la mejor prote
    SYMBOL ' (237)
    TEXT na en cuanto a calidad/precio del re
    SYMBOL ' (241)
    TEXT ido mercado de la nutrici
    SYMBOL ' (243)
    TEXT n deportiva.
    WORD par (1)
    WORD par (1)
    WORD par (1)
    WORD b (1)
    TEXT VIT.O.BEST WHEY PROTEIN 100% 24B
    WORD b (0)
    TEXT . es una prote
    SYMBOL ' (237)
    TEXT na perfecta para el uso diario, que adem
    SYMBOL ' (225)
    TEXT s tiene una buena capacidad de absorci
    SYMBOL ' (243)
    TEXT n y una velocidad de absorci
    SYMBOL ' (243)
    TEXT n media.
    WORD par (1)
    WORD par (1)
    WORD par (1)
    WORD b (1)
    TEXT VIT.O.BEST WHEY PROTEIN 100%
    WORD b (0)
    TEXT tiene una gran variedad de sabores deliciosos y muy suaves perfectos para el uso diario sin que terminen siendo empalagosos o
    WORD b (1)
    TEXT aburridos. WHEY PROTEIN 100%
    WORD b (0)
    TEXT est
    SYMBOL ' (225)
    TEXT disponible en sabor a chocolate, yogur de lim
    SYMBOL ' (243)
    TEXT n , fresa, crema de caf
    SYMBOL ' (233)
    TEXT y vainilla.
    WORD b (1)
    TEXT VIT.O.BEST WHEY PROTEIN 100%
    WORD b (0)
    TEXT es una prote
    SYMBOL ' (237)
    TEXT na muy pura que no contiene az
    SYMBOL ' (250)
    TEXT car y est
    SYMBOL ' (225)
    TEXT totalemente libre de aspartamo.
    WORD par (1)
}

**Comment by henck** [comment]
I was able to replicate your result. There was in fact a bug where the method is_letter did not correctly recognize letters. This is why is could happen that `\pard\b\f` was read as a single control word, while it's in fact three control words (`\pard`, `\b` and `\f`). This is now fixed and your text appears properly bolded.
