### ISSUE TITLE
Error installation via composer

### ISSUE THREAD

**Issue by pierre-H** [henck/rtf-html-php#14]
Hello,
When I try to install via composer, I get this message : 

`Could not find package henck/rtf-to-html at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

What can I do ?

**Comment by henck** [comment]
Your composer is set to only allow installation of packages marked as stable, which is the default. See [here](http://webtips.krajee.com/setting-composer-minimum-stability-application/) for instructions on how to disable this requirement and allow installation of rtf-to-html.
