### ISSUE TITLE
Too many span tags - every(!) umlaut wrapped in span tag

### ISSUE THREAD

**Issue by lbm-services** [henck/rtf-html-php#17]
Hi,
the conversion works principally fine, but produces ugly html with lots of span tags where none were required, actually EVERY umlaut (&ouml;/&auml;/&uuml;)  is wrapped with span tags!

e.g.

```html 
raffte mehr als die H</span><span style='font-size: 14px;'>&auml;</span><span style='font-size: 14px;'>lfte der Bev</span><span style='font-size: 14px;'>&ouml;</span><span style='font-size: 14px;'>lkerung dahin.
```
here is my rtf source:

```rtf
raffte mehr als die H\'e4lfte der Bev\'f6lkerung dahin. 
```

**2.Problem**
u8211 should be converted to something like &amp;ndash; (&ndash;) or &amp;mdash; (&mdash;) but is converted to &amp;loz; (&loz;)

```rtf
beklagt sich \u8211 - f\'fcr deutsche Leser
```

```html 
beklagt sich </span>&loz;<span style='font-size: 14px;'>- f</span><span style='font-size: 14px;'>&uuml;</span><span style='font-size: 14px;'>r deutsche Leser
```

**Comment by boomsya** [comment]
look my solution: https://github.com/henck/rtf-html-php/issues/23

**Comment by boomsya** [comment]
about tons of span :) at now i try to optimize algorithm

**Comment by boomsya** [comment]
my old converted file into HTML was 144 KB and after optimization new file is 9KB
modified file on Google Drive: https://drive.google.com/open?id=0Bz8kyWHfJdSRSzRhT25LNncyYlU
