### ISSUE TITLE
Storing return object as string

### ISSUE THREAD

**Issue by imperimus** [henck/rtf-html-php#2]
There does not seem to be a way to stored the html in a string or array, either by directly using or returning from a function. Not sure if it is related but also if I do an echo in a foreach loop i only get two of my 6 strings.

foreach($letter_para as $para){
                $reader = new RtfReader();
                $reader->Parse($para["ParagraphText"]);
                $formatter = new RtfHtml();
                //$reader->root->dump();
                $html .= $formatter->Format($reader->root);
}

The dump does show data, again only for two of the 6.

Thanks for the effort and thank you for sharing!

**Comment by henck** [comment]
I can't duplicate this. When I feed in short RTF texts in a loop, I get output for all of them. Can you make your sample data available?
