### ISSUE TITLE
Erreor with this RTF char : \u233

### ISSUE THREAD

**Issue by Max84** [henck/rtf-html-php#20]
Hi,

This my RTF string:
{\rtf1\deff0{\fonttbl{\f0 Calibri;}{\f1 Microsoft Sans Serif;}}{\colortbl ;\red0\green0\blue255 ;}{\*\defchp \fs22}{\stylesheet {\ql\fs22 Normal;}{\*\cs1\fs22 Default Paragraph Font;}{\*\cs2\sbasedon1\fs22 Line Number;}{\*\cs3\ul\fs22\cf1 Hyperlink;}{\*\ts4\tsrowd\fs22\ql\tscellpaddfl3\tscellpaddl108\tscellpaddfb3\tscellpaddfr3\tscellpaddr108\tscellpaddft3\tsvertalt\cltxlrtb Normal Table;}{\*\ts5\tsrowd\sbasedon4\fs22\ql\trbrdrt\brdrs\brdrw10\trbrdrl\brdrs\brdrw10\trbrdrb\brdrs\brdrw10\trbrdrr\brdrs\brdrw10\trbrdrh\brdrs\brdrw10\trbrdrv\brdrs\brdrw10\tscellpaddfl3\tscellpaddl108\tscellpaddfr3\tscellpaddr108\tsvertalt\cltxlrtb Table Simple 1;}}{\*\listoverridetable}\nouicompat\splytwnine\htmautsp\sectd\pard\plain\ql{\f1\fs17\cf0 100% polyester r\u233\'e9sistant Les coutures sont renforc\u233\'e9es et les bords sont doubles}\f1\fs17\par}

I get this:
100% polyester r◊'e9sistant Les coutures sont renforc◊'e9es et les bords sont doubles

Instead of this:
100% polyester résistant Les coutures sont renforcées et les bords sont doubles

I think it's due to this rtf char not properly filtered "\u233"

I hope this report will help this amazing tool 👍  !!!

**Comment by henck** [comment]
Support for Unicode characters was added just now. Does it solve the problem?
