### ISSUE TITLE
A great script but unfortunately with umlauts like ä, ö, ü, etc. it is not.

### ISSUE THREAD

**Issue by dieterdd** [henck/rtf-html-php#27]
A great script but unfortunately with umlauts like ä, ö, ü, etc. it is not.
"können" is "kamp;apos;f6nnen" 
 Can someone help me here. Thank you and best regards Dieter

**Comment by mhtamala** [comment]
can you post your RTF file so I can reproduce the error ?

**Comment by derbergbordesholm** [comment]
nearly the same Problem here : 
{\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fnil\fcharset0 Futura Md BT;}} {\colortbl ;\red0\green0\blue0;} \viewkind4\uc1\pard\cf1\lang1031\f0\fs22 Mindestbestellmenge: 100 St\'fcck\par } 

returns :    Mindestbestellmenge: 100 St ü ck

example : üüü is : ü ü ü 

Can somebody help ?

**Comment by mhtamala** [comment]
hello, 
that piece of RTF does not comply with RTF Specification v1.5. It should be:

> {\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fnil\fcharset0 Futura Md BT;}} {\colortbl ;\red0\green0\blue0;} \viewkind4\uc1\pard\cf1\lang1031\f0\fs22 Mindestbestellmenge: 100 St\\'fcck\par }


please use the last version of the Rtf class and make sure you are forcing  browser to use utf8 encoding.
Regards
