### ISSUE TITLE
only first underline is working

### ISSUE THREAD

**Issue by Scheissy** [henck/rtf-html-php#29]
i got an issue with a text that contains more than one word or phrase that's underlined. the first one gets displayed fine, but the second (or third) time an underlining is used is not working.

example:
`{\rtf1\ansi\deff0{\fonttbl{\f0\fnil Microsoft Sans Serif;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
{\colortbl ;\red0\green0\blue0;}
\viewkind4\uc1\pard\lang1031\f0\fs17 Filterdichtung f\f1\'fcr Jupiter Gebl\'e4seeinheit \par
\par
\cf1\ul\b\'dcberschrift 1 - fett + unterstrichen:\cf0\ulnone\b0\par
\par
Test text 1\par
\par
\cf1\ul\b\'dcberschrift 2 - fett + unterstrichen:\cf0\ulnone\b0\par
\par
Test text 2\par
\par
\cf1\ul\b\'dcberschrift 3 - fett + unterstrichen:\cf0\ulnone\b0\par
\par
Test text 3\f0\par
}`

> Überschrift 1 - fett + unterstrichen:

is underlined (and bold) nicely. 

> Überschrift 2 - fett + unterstrichen: 

is just bold, but not underlined.

thanks for your help!

**Comment by mhtamala** [comment]
You are right thanks for reporting this bug. please try the proposed fix and report on.
best regards

**Comment by Scheissy** [comment]
looks good now. thank u very much!
