### ISSUE TITLE
Returning false.

### ISSUE THREAD

**Issue by iqbalmalik89** [henck/rtf-html-php#33]
This is returning false. 

```
$reader = new RtfReader();
$rtf = file_get_contents("example.rtf"); // or use a string
$result = $reader->Parse($rtf);
echo "<pre>";
var_dump($result);
```

Any help?

**Comment by mhtamala** [comment]
Hi, definitely the script is not able to find a file with the name "example.rtf" please check php error log.
Regards

**Comment by henck** [comment]
Either that, or a parse error has occurred. Parse errors are logged as PHP notices, so yes, please check the error log.
