### ISSUE TITLE
Conversion of escaped characters is wrong

### ISSUE THREAD

**Issue by kschroeer** [henck/rtf-html-php#35]
The conversion of escaped characters is wrong.

For example I have the following RTF:

    {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
    {\*\generator Riched20 6.3.9600}\viewkind4\uc1 
    \pard\sa200\sl276\slmult1\f0\fs22\lang7 Hello \{World\}\par
    }

The HTML snippet looks like this:

    <span style="font-size: 19px;">Hello {{World}}</span><p>

But the correct result would be:

    <span style="font-size: 19px;">Hello {World}</span><p>

And it's the same with other characters, for example the backslash:

    {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
    {\*\generator Riched20 6.3.9600}\viewkind4\uc1 
    \pard\sa200\sl276\slmult1\f0\fs22\lang7 C:\\Windows\par
    }

Results in a string with double backslash:

    <span style="font-size: 19px;">C:\\Windows</span><p>

**Comment by mhtamala** [comment]
Thanks for reporting the Issue, please try the following fix https://github.com/mhtamala/rtf-html-php/blob/patch-2/rtf-html-php.php
waiting for feedback
thanks

**Comment by kschroeer** [comment]
Thank you for your quick response and especially the bug fix.
I can report: it works!
