### ISSUE TITLE
Conversion always returns  "1"

### ISSUE THREAD

**Issue by Efimerex** [henck/rtf-html-php#39]
Hello,
I´m doing some trials with this simple code

require("rtf2html.php");
$reader = new RtfReader();
$rtf = file_get_contents("temp/cs.rtf");
if($cb = $reader->Parse($rtf))
echo $cb;

But I´m always getting "1" as Parse($rtf) response.
Curiously if I and a $reader->root->dump();
then I can see the rtf tree on screen...

What do you think that It would be happening with this?

Thank you so much for your help.

**Comment by Efimerex** [comment]
I´m sorry seems that It was my fault.
When I run those commands

$formatter = new RtfHtml();
echo $formatter->Format($reader->root)

I noticed that returns a "Call to undefined function mb_convert_encoding() " error.

Seems that I need to re-install the php-mbstring module on my server.

Regards,

**Comment by henck** [comment]
Well, thanks anyway for the report. I've now included this issue as a "caveat" in the project description so that others know about this pitfall.
