### ISSUE TITLE
Parse into variables

### ISSUE THREAD

**Issue by MonakaDev** [henck/rtf-html-php#46]
Hi,

It is a really good HTML Parser but I've got a question. What if, instead of parsing into HTML, I wanted to parse the document into multiple php variables so I could re-use these ones for something else.
How could I do that ?

Thanks

**Comment by mhtamala** [comment]
I understand the idea but it is still vague. considering this is an rtf to html formatter I think this is out of scope of the project. but you can parse the `$root` property of the `RtfReader` class to anything you want.
If the project had hat an Interpreter layer between the `RtfReader` and `RtfHtml` that could ease your work but unfortunately not. Maybe that will be planned in the future.

**Comment by MonakaDev** [comment]
Ok, I guess I could parse the spans into variables. I hope I can make it work ahah.
Thanks for the help.

**Comment by henck** [comment]
The Html formatter is separate from the RTF parser. The parser creates a syntax tree which you can access through `$reader->root`. From there, you could add a new formatter. I've actually moved the HTML formatter into its own namespace. In the future, other formatters could be added like XML, for instance. For the time being, I am closing this issue.
