### ISSUE TITLE
Update Packagist entry

### ISSUE THREAD

**Issue by henck** [henck/rtf-html-php#63]
Hello @bretto36

I see that the composer package for this project is maintained by you. I'd like to update it to reflect the latest commits, but you are now managing the vendor name "henck".

Also, the package name on Packagist is "rtf-to-html", while it should be "rtf-html-php", to conform to the name of this Github repository.

What can be done? Can you make me a maintainer of the package, as well?

**Comment by bretto36** [comment]
@henck  - Can you tell me your Packagist username and i will add you

I have updated the packagist entry for now so it has branch 1.1

Apologies for the delay

**Comment by henck** [comment]
@bretto36 Thank you! My packagist username is henck.

**Comment by bretto36** [comment]
Apologies again for the delay. You are now a maintainer.
