### ISSUE TITLE
RTF Truncated

### ISSUE THREAD

**Issue by wildrove** [henck/rtf-html-php#65]
Hi,
I'm having some problems when I call `$document = new Document($evolution);`
one Exception error is threw: 
**Notice: Parse error: Tried to read past end of input; RTF is probably truncated. in C:\xampp\htdocs\App_prontuario\RtfHtmlPhp\Document.php on line 29**
I'm making a query in a database and I take the return query and I put in a variable how you can see below:
`<?php

	session_start();
	require '../../vendor/autoload.php';

	use Classes\Pacient\PacientEvolution\PacientEvolution;

	$pacientRegistry = intval($_GET['prontuario']);

	$pacientEvolution = new PacientEvolution();
	$pacientEvo = $pacientEvolution->findPacientEvolution($pacientRegistry);

	$evolution = null;

	foreach ($pacientEvo as $key => $value) {
		if ($pacientEvo[$key]['EVOLUCAO']) {
			$evolution = $pacientEvo[$key]['EVOLUCAO'];
		}

	}

	use RtfHtmlPhp\Document;
	$document = new Document($evolution);`

But I don't know what is happening, can someone help me? I'm for 3 days looking for some solution to show the RTF content but I can't do yet.

**Comment by mhtamala** [comment]
Hi @wildrove and sorry for the inconvenience.

If somehow `$pacientEvo[$key]['EVOLUCAO']` returns an empty string then if-statement would be TRUE and $evolution will store that empty string which makes `RtfHtmlPhp` always throwing that exception considering an empty string is not a valid RTF document.

Please debug your code and check what contents the `$evolution` variable passes to the `HtmlRtfPhp` module.

only then If you still encounter the same problem then please append the RTF string that causes the trouble.

Regards

**Comment by mhtamala** [comment]
Hi @wildrove and sorry for the inconvenience.

Please debug your code and check what contents the $evolution variable passes to the HtmlRtfPhp module. If you still encounter the same problem then please append the RTF string that causes the trouble.

Regards

**Comment by bretto36** [comment]
@wildrove  If you are retrieving the value from the DB, it's highly likely the DB column isn't large enough. Change to LONGTEXT if using mysql.

**Comment by Leshana** [comment]
@wildrove I have noticed in my own testing that RTF files saved with WordPad or MS Word have a null byte (0x00) on the end of the file _after_ the closing `}`. I get the same error as you when attempting to parse those files.
If your error is the same cause, you can work around it by using `rtrim($evolution)` to chop it off.

**Comment by wildrove** [comment]
Hi Everyone,
Thank you for your support. I've stopped with this project for some months, but I started it again. And I   keep getting the same errors. I'll try to explain better my issues this time. I'm using a Firebird Database and the table which I'm receiving the Rtf data is that in this image :
![Colummn BLOB](https://user-images.githubusercontent.com/29077046/81959144-6606ea00-95e5-11ea-9a49-0fcdf8d079b7.png). As you can see is a BLOB Column I'm novice in PHP and I don't know BLOB type. Below there is an example of rtf file came from this column, I debugged using var_dump() function to show here.
[rtf.txt](https://github.com/henck/rtf-html-php/files/4629636/rtf.txt).  Below there is de php file where I'm trying to run some tests but I keep getting the same issues yet.
`<?php
	
	session_start();
	require '../../vendor/autoload.php';
	
	use Classes\Pacient\PacientEvolution\PacientEvolution;
	use RtfHtmlPhp\Document;
	use RtfHtmlPhp\Html\HtmlFormatter;

	$pacientProntuary = intval($_GET['regProntuary']);
	$pacientRegistry = (isset($_GET['regPacient']) ? intval($_GET['regPacient']) : "");
	$hourEvo = $_GET['hourEvolution'];
	$dateEvo = $_GET['dateEvolution'];
	$pacientName = (isset($_GET['pacientName']) ? $_GET['pacientName'] : "");
	$mother = (isset($_GET['mother']) ? $_GET['mother'] : "");
	$birthday = (isset($_GET['birthday']) ? date('d/m/Y', strtotime($_GET['birthday'])) : "");
	$type = (isset($_GET['type']) ? $_GET['type'] : "");
	$resumeType = (isset($_GET['resumeType']) ? $_GET['resumeType'] : "");

	$pacientEvolution = new PacientEvolution();
	$rtf;
	$pacientEvo = $pacientEvolution->pacientEvo($pacientProntuary,$dateEvo,$hourEvo);

	foreach ($pacientEvo as $key => $value) {
		$rtf = $pacientEvo[$key]['EVOLUCAO'];
	}
	$document = new Document($rtf);
	echo $document;`

![rtf error](https://user-images.githubusercontent.com/29077046/81960575-8c2d8980-95e7-11ea-9338-c1fe9c68320c.png)
Is there a way to fix this issues? I can't find any solution to this.

**Comment by wildrove** [comment]
> @wildrove I have noticed in my own testing that RTF files saved with WordPad or MS Word have a null byte (0x00) on the end of the file _after_ the closing `}`. I get the same error as you when attempting to parse those files.
> If your error is the same cause, you can work around it by using `rtrim($evolution)` to chop it off.

Hi @Leshana thank you for your tip. I used trim() and worked for me. I don't know what happend but worked. But unfortunately grids are removed from tables presents in some string.

**Comment by fialhoFabio** [comment]
@wildrove if u wanna to maintain the grid, u only need to use rtrim($evolution, "\0");
