### ISSUE TITLE
Real world example of rtf not being touched by this

### ISSUE THREAD

**Issue by sunnyjayjay** [henck/rtf-html-php#8]
I am finding it mostly does not work. Here is an example:

> { tf1ansideff0{fonttbl{f0fnilfcharset0 Arial;}{f1fnil Arial;}} viewkind4uc1pardlang2057fs18 Handbuilt bowl with large crab in blacks and yellowsf1par } 

Running that through your routine results in 

> tf1ansideff0fonttblf0fnilfcharset0 Arial;f1fnil Arial;viewkind4uc1pardlang2057fs18 Handbuilt bowl with large crab in blacks and yellowsf1par 

whereas what is needed is

> Handbuilt bowl with large crab in blacks and yellows

**Comment by Okcuoglu** [comment]
you don't have a real rtf version definition the "r" is missing. This Works very fine in my case with correct headers.

**Comment by sunnyjayjay** [comment]
Can you let me see your "correct" headers please?

**Comment by Okcuoglu** [comment]
well for startes... i would suggest you put the letter "r" after your { so the parser knows what to parse. that could help if you use that rtf string you have postet 

also slashes would be helpful so the parser knows where to start and where to stop
you can see an example of my "correct" rtf string on the following lines 

{\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fnil\fcharset0 Arial;}{\f1\fnil\fcharset0 MS Shell Dlg 2;}}
{\*\generator Richedit 5.41.15.1507;}\viewkind4\uc1\pard\fi852\i\fs16 --------------------------------------------------------------------\par
\pard\par
\f1\fs17\par
}

**Comment by sunnyjayjay** [comment]
So without the "correct" header it cannot work. Thanks.

**Comment by Okcuoglu** [comment]
yes that's it, you got it buddy. Every text or fileformat needs a definition so it can be parsed. With the  "correct" header you tell the parser all the details you have in your rtf string lilke which rtf document version or which fonts you are using in your document. 

for detailled information have a look at http://www.biblioscape.com/rtf15_spec.htm 


you're welcome.

**Comment by henck** [comment]
Although this sample file does not appear to begin with `{\rtf1` as all RTF files should, I think in fact it did. When @sunnyjayjay dumped the RTF content, the `\r` was printed as a newline and disappeared. (in fact, all backslashes are gone from their dump). 

If the RTF content was indeed fed into the parser _after_ all ASCII control codes were removed, then the parser cannot work. I am closing the issue for now.
