### ISSUE TITLE
PHP Fatal error:   Call to a member function GetType() on a non-object in C:\....\lib\rtf-html-php\rtf-html-php.php on line 400

### ISSUE THREAD

**Issue by yourchoice** [henck/rtf-html-php#9]
PHP Fatal error:   Call to a member function GetType() on a non-object in C:....\lib\rtf-html-php\rtf-html-php.php on line 400

**Comment by sasosmolej** [comment]
This issue appears if you try to parse an empty string - the parser returns true (for some reason) without issues, but the formatter throws an error.

Workaround:
`if (strlen($text) < 1) return $text;
$reader = new RtfReader();
$reader->Parse($text);`

I would imagine this doesn't fix every possible case, but it should fix the most common one.

**Comment by henck** [comment]
I've added a test case for the empty string.
